server:
  port: 8088
  tomcat:
    max-swallow-size: -1
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS
  #servlet:
  #  context-path: /qwghwork
  #session:
  #  cookie:
  #    http-only: true
  #    secure: true
  #    encoding:
  #      force: true
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

management:
  endpoints:
    web:
      exposure:
        include: metrics,httptrace

spring:
  devtools:
    restart:
      additional-paths: src/main/java
    exclude: static/**,public/**
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 2048MB

  ## quartz定时任务,采用数据库方式

  #json 时间戳统一转换
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
    serialization:
      write-dates-as-timestamps: false
  jpa:
    open-in-view: false

  aop:
    proxy-target-class: true
  #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/html/
    suffix: .html
    mode: HTML5
    check-template-location: true
    encoding: UTF-8
    content-type: text/html
    enabled: true
    cache: false
  #配置freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    prefix:
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefer-file-system-access: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
  # 设置静态文件路径，js,css等
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: jsp
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  #autoconfigure:
  #  exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.3.4:3306/szgq_workflow?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://localhost:3306/szgq_workflow?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://172.81.208.49:3306/szgq_workflow?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Lizhihong@2019
    #password: 123456
    #password: Hpi2022
    driver-class-name: com.mysql.cj.jdbc.Driver
  #          url: jdbc:oracle:thin:@localhost:1521:oralin
  #          username: jeecgnew
  #          password: jeecgnew
  #          driver-class-name: oracle.jdbc.driver.OracleDriver

  #redis 配置
#  redis:
#    database: 0
#    host: 127.0.0.1
#    lettuce:
#      pool:
#        max-active: 8   #最大连接数据库连接数,设 -1 为没有限制
#        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
#        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
#        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
#      shutdown-timeout: 100ms
#    password: ''
#    port: 6379
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:com/hpi/modules/**/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      db-config:
        field-strategy: NOT_EMPTY
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true

#是否激活 swagger true or false
swagger:
  enable: true

#Mybatis输出sql日志

logging:
  #config: classpath\:log4j2.xml
  level:
    com.hpi.modules.system.mapper : info
#企业微信配置
#宏湃
hpi:
  weixin:
    corpid: wx1c0aa9f1985dd1f4
    secret: cNkcGymXq-pa2yZpWZAfVgNN3u4SZ9Jke8fQBDe2GT4
    agentid: 1000005
    scanQRCodeUrl: https\://www.gzihp.cn/hnyh/elink/scanorcode



